### PR TITLE
patch with win32 fixes from lua-linenoise-windows and cross fingers

### PR DESCRIPTION
**Pull request by cmsd2**
i've done a big old merge taking the files from lua-linenoise-windows on the left side and rust-linenoise on the right and forced them to mate.

the rust-linenoise example compiles and runs on windows, with some escape character weirdness.

this is not to suggest you actually merge this pull request.. i think it's rather horrible actually,
but i had to start somewhere, and someone else might find it useful.

### CODE REVIEW

**Comment by octplane** [comment]
I'll review it today or tomorrow but I'm rather in favor of integrating the merge. If any bug pops out we shall see. The library is not popular enough to have angry users throwing threats at me... And having a win32 support is very cool, thanks!

**Comment by octplane** [comment]
If you want to integrate https://github.com/octplane/rust-linenoise/commit/b87f2772b8f6d699b0369e436ba17290bd62b16d in your changes, this should fix the build.

**Comment by cmsd2** [comment]
build fixed.

**Comment by octplane** [comment]
Thank you. Will release shortly...

**Pull request merged**
